"""Personalised advice line — CLAUDE.md non-negotiable rule: "Every screening
result must carry a personalised advice line. A result without one is
incomplete." SILICAGUARD.md Section 11: "a single sentence, drawn from the
miner's own weakest answer, telling him the one thing that will most change
his outcome."

Deliberately NOT generated by the model as free-form text. CLAUDE.md's AI
governance rule is explicit: "No AI output reaches a patient as free-form
text — patient-facing content is template-bound and clinician-approved."
So this picks the miner's single worst-scoring answer and returns a fixed,
pre-written sentence for that (question_code, answer_value) pair — the same
sentence every time the same weakest answer occurs, auditable and reviewable
as a fixed list rather than regenerated per call.

DRAFT COPY. The templates below are placeholder English text written to get
the mechanism working end-to-end for today's demo scope. Per CLAUDE.md:
"Every patient-facing string requires the Clinical Lead's written sign-off
before it ships" — none of this text has that sign-off yet, and Shona
translations don't exist yet either (SILICAGUARD.md still requires
Shona/English for anything miner-facing). Do not treat this copy as final.
"""

from typing import List

from models import ScreeningAnswerIn

# question_code -> {answer_value: advice line}. Only entries for answer
# values that actually indicate a problem — a "best" answer (e.g. always
# wears N95) has nothing to advise against, so it's absent here.
ADVICE_TEMPLATES = {
    "PPE_USE": {
        "never": "Always wear an N95 or FFP2 mask when drilling or crushing — this is the single biggest thing you can change.",
        "cloth_mask": "Swap your cloth or surgical mask for a proper N95/FFP2 respirator — cloth masks don't stop silica dust.",
        "sometimes": "Wear your N95 mask every time you drill or crush, not just sometimes.",
    },
    "WET_DRILLING": {
        "never": "Ask your site to use water suppression (wet drilling) — it cuts the dust you breathe dramatically.",
        "sometimes": "Ask for water suppression every time you drill, not just sometimes.",
    },
    "BREATHLESSNESS": {
        "severe": "Your breathlessness needs urgent medical attention — go to the clinic today, do not wait.",
        "moderate": "Tell the clinic about your breathlessness at your next visit — it's an early warning sign worth tracking.",
    },
    "COUGH_DURATION": {
        "severe": "A cough that has lasted this long needs to be checked by a clinician as soon as possible.",
        "mild": "Keep track of your cough — if it hasn't cleared in a few weeks, get it checked.",
    },
    "CHEST_PAIN": {
        "severe": "Chest pain like this needs urgent medical attention — go to the clinic today.",
        "sometimes": "Mention your chest pain at your next clinic visit, even if it comes and goes.",
    },
    "TB_HISTORY": {
        "current": "Keep taking your TB treatment exactly as prescribed — stopping early is dangerous, especially with dust exposure.",
        "past": "Because you've had TB before, watch closely for any new cough or breathlessness and report it early.",
    },
    "WEIGHT_LOSS": {
        "significant": "Unexplained weight loss needs a clinical check — mention it at your next visit.",
        "some": "Keep an eye on your weight — mention any further loss at your next visit.",
    },
    "PRIOR_LUNG_DIAGNOSIS": {
        "yes": "Because you already have a lung diagnosis, treat any new or worsening symptom as urgent.",
    },
    "YEARS_UNDERGROUND": {
        "over_10": "With over 10 years of exposure, keep up regular re-screening even when you feel fine.",
    },
    "JOB_ROLE": {
        "drilling": "Drilling carries the highest dust exposure on site — make wet drilling and your N95 mask non-negotiable.",
        "crushing": "Crushing carries high dust exposure — make wet suppression and your N95 mask non-negotiable.",
    },
}

GREEN_DEFAULT_ADVICE = (
    "Keep doing what you're doing — always wear your N95 mask and ask for "
    "wet drilling whenever it's available."
)


def personalised_advice_line(answers: List[ScreeningAnswerIn]) -> str:
    """Every result must carry a line, so this always returns one — falling
    back through progressively lower-scoring answers before landing on the
    GREEN default, rather than ever returning None."""
    scored = sorted(
        (a for a in answers if a.answer_score > 0),
        key=lambda a: a.answer_score,
        reverse=True,
    )
    for answer in scored:
        line = ADVICE_TEMPLATES.get(answer.question_code, {}).get(answer.answer_value)
        if line:
            return line

    return GREEN_DEFAULT_ADVICE
