"""initial schema

Revision ID: 0ae36e3a6a65
Revises: 
Create Date: 2026-08-15 23:14:50.234305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae36e3a6a65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('mine_site', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('mines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('province', sa.String(), server_default=sa.text("'Midlands'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outreach_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('expected_headcount', sa.Integer(), nullable=True),
    sa.Column('screened_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('health_workers', sa.String(), nullable=True),
    sa.Column('report_generated', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sms_3day_sent', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('sms_1day_sent', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), server_default=sa.text("'sms'"), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.CheckConstraint("delivery_status IN ('sent','failed','skipped')", name='ck_notifications_delivery_status'),
    sa.ForeignKeyConstraint(['worker_id'], ['miners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('miner_id', sa.Integer(), nullable=True),
    sa.Column('previous_screening_id', sa.Integer(), nullable=True),
    sa.Column('screened_by', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('advice_line', sa.Text(), nullable=True),
    sa.Column('ai_explanation_shona', sa.Text(), nullable=True),
    sa.Column('ai_explanation_english', sa.Text(), nullable=True),
    sa.Column('ai_contributing_factors', sa.Text(), nullable=True),
    sa.Column('provisional', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('fallback_used', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('synced', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('outreach_visit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("tier IN ('GREEN','YELLOW','ORANGE','RED')", name='ck_screenings_tier'),
    sa.ForeignKeyConstraint(['miner_id'], ['miners.id'], ),
    sa.ForeignKeyConstraint(['outreach_visit_id'], ['outreach_visits.id'], ),
    sa.ForeignKeyConstraint(['previous_screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('miner_id', sa.Integer(), nullable=True),
    sa.Column('hospital', sa.String(), server_default=sa.text("'Kwekwe District Hospital'"), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('pre_alert_sent', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'open'"), nullable=True),
    sa.Column('reminder_stage', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("status IN ('open','pre_alerted','reminded','attended','closed','escalated')", name='ck_referrals_status'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['miner_id'], ['miners.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_table('screening_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('question_code', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('answer_value', sa.String(), nullable=True),
    sa.Column('answer_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_answers')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('screenings')
    op.drop_table('notifications')
    op.drop_table('outreach_visits')
    op.drop_table('mines')
    op.drop_table('miners')
    op.drop_table('facilities')
    # ### end Alembic commands ###
