"""add keepalive_pings table

Revision ID: a97c1fa69c0e
Revises: 0ae36e3a6a65
Create Date: 2026-08-16 00:25:15.205491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97c1fa69c0e'
down_revision: Union[str, Sequence[str], None] = '0ae36e3a6a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keepalive_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinged_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keepalive_pings')
    # ### end Alembic commands ###
